/* eslint-disable */
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteFileKey, RouteLayoutKey, RawRouteComponent } from "@elegant-router/types";

export const layouts: Record<RouteLayoutKey, RawRouteComponent> = {
  base: () => import("@/layouts/base/index.vue"),
  blank: () => import("@/layouts/blank/index.vue"),
};

export const views: Record<RouteFileKey, RawRouteComponent> = {
  _builtin403: () => import("@/views/_builtin/403/index.vue"),
  _builtin404: () => import("@/views/_builtin/404/index.vue"),
  _builtin500: () => import("@/views/_builtin/500/index.vue"),
  _builtinIframePageUrl: () => import("@/views/_builtin/iframe-page/[url].vue"),
  Home: () => import("@/views/home/index.vue"),
  Test: () => import("@/views/test/index.vue"),
};
