/* eslint-disable */
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { AutoRouterRoute } from '@elegant-router/types';

export const routes: AutoRouterRoute[] = [
  {
    name: "Root",
    path: "/",
    redirect: "/home",
    meta: {
      title: "Root",
      constant: true,
    },
  },
  {
    name: "NotFound",
    path: "/:pathMatch(.*)*",
    layout: "base",
    component: "NotFound",
    meta: {
      title: "404 Not Found",
      constant: true,
    },
  },
  {
    name: "_builtin403",
    path: "/_builtin/403",
    layout: "base",
    component: "_builtin403",
    meta: {
      title: "403 Forbidden",
      constant: true,
    },
  },
  {
    name: "_builtin404",
    path: "/_builtin/404",
    layout: "base",
    component: "_builtin404",
    meta: {
      title: "404 Not Found",
      constant: true,
    },
  },
  {
    name: "_builtin500",
    path: "/_builtin/500",
    layout: "base",
    component: "_builtin500",
    meta: {
      title: "500 Internal Server Error",
      constant: true,
    },
  },
  {
    name: "Home",
    path: "/home",
    layout: "base",
    component: "Home",
    meta: {
      title: "home",
      icon: "mdi:home",
    },
  },
  {
    name: "Test",
    path: "/test",
    layout: "base",
    component: "Test",
    meta: {
      title: "home",
      localIcon: "vue",
    },
  }
];
