/* eslint-disable */
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { AutoRouterRoute } from '@elegant-router/types';

export const routes: AutoRouterRoute[] = [
  {
    name: 'Root',
    path: '/',
    redirect: '/home',
  },
  {
    name: 'NotFound',
    path: '/:pathMatch(.*)*',
    layout: 'base',
    component: 'NotFound',
  },
  {
    name: '_builtin403',
    path: '/_builtin/403',
    layout: 'base',
    component: '_builtin403',
  },
  {
    name: '_builtin404',
    path: '/_builtin/404',
    layout: 'base',
    component: '_builtin404',
  },
  {
    name: '_builtin500',
    path: '/_builtin/500',
    layout: 'base',
    component: '_builtin500',
  },
  {
    name: '_builtinIframePageUrl',
    path: '/_builtin/iframe-page/:url',
    layout: 'base',
    component: '_builtinIframePageUrl',
  },
  {
    name: 'Home',
    path: '/home',
    layout: 'base',
    component: 'Home',
  },
  {
    name: 'Test',
    path: '/test',
    layout: 'base',
    component: 'Test',
  }
];
