/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hidden: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hidden: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hidden: true
    }
  },
  {
    name: 'form',
    path: '/form',
    component: 'layout.base$view.form',
    meta: {
      title: 'form',
      i18nKey: 'route.form'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'carbon:home'
    }
  },
  {
    name: 'test1',
    path: '/test1',
    component: 'layout.base',
    meta: {
      title: 'test1',
      i18nKey: 'route.test1'
    },
    children: [
      {
        name: 'test1_test11',
        path: '/test1/test11',
        component: 'view.test1_test11',
        meta: {
          title: 'test1_test11',
          i18nKey: 'route.test1_test11'
        }
      }
    ]
  },
  {
    name: 'v1',
    path: '/v1',
    component: 'layout.base',
    meta: {
      title: 'v1',
      i18nKey: 'route.v1'
    },
    children: [
      {
        name: 'v1_v2',
        path: '/v1/v2',
        meta: {
          title: 'v1_v2',
          i18nKey: 'route.v1_v2'
        },
        children: [
          {
            name: 'v1_v2_v3',
            path: '/v1/v2/v3',
            component: 'view.v1_v2_v3',
            meta: {
              title: 'v1_v2_v3',
              i18nKey: 'route.v1_v2_v3'
            }
          }
        ]
      }
    ]
  }
];
