/* eslint-disable */
// @ts-nocheck
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

export {}

declare module "vue-router" {
  type RouteNamedMap = import("vue-router/auto-routes").RouteNamedMap;

  export interface TypesConfig {
    RouteNamedMap: RouteNamedMap;
  }
}

declare module "vue-router/auto-routes" {
  import type { RouteParamsRawGeneric, RouteParamsGeneric, RouteMeta, RouteRecordInfo, ParamValue, ParamValueZeroOrOne } from "vue-router";

  /**
   * route named map
  */
  export interface RouteNamedMap {
    "Root": RouteRecordInfo<"Root", "/", Record<never, never>, Record<never, never>>;
    "NotFound": RouteRecordInfo<"NotFound", "/:pathMatch(.*)*", Record<never, never>, Record<never, never>>;
    "_builtin403": RouteRecordInfo<"_builtin403", "/_builtin/403", Record<never, never>, Record<never, never>>;
    "_builtin404": RouteRecordInfo<"_builtin404", "/_builtin/404", Record<never, never>, Record<never, never>>;
    "_builtin500": RouteRecordInfo<"_builtin500", "/_builtin/500", Record<never, never>, Record<never, never>>;
    "_builtinIframePageUrl": RouteRecordInfo<"_builtinIframePageUrl", "/_builtin/iframe-page/:url", { url: ParamValue<true> }, { url: ParamValue<false> }>;
    "Home": RouteRecordInfo<"Home", "/home", Record<never, never>, Record<never, never>>;
    "Test": RouteRecordInfo<"Test", "/test", Record<never, never>, Record<never, never>>
  }
}
